Repository kids-first/kf-cbioportal-etl, pull requests merged in 2025-04, with the labels that each got.

#83 🧹 Code Linting
  .gitignore
  cbioportal_etl/scripts/check_downloads.py
  cbioportal_etl/scripts/cnv_1_genome2gene.py
  cbioportal_etl/scripts/cnv_2_merge.py
  cbioportal_etl/scripts/cnv_3_gistic_style.py
  cbioportal_etl/scripts/cnv_merge_seg.py
  cbioportal_etl/scripts/convert_fusion_as_sv.py
  cbioportal_etl/scripts/diff_studies.py
  cbioportal_etl/scripts/genomics_file_cbio_package_build.py
  cbioportal_etl/scripts/get_file_metadata_helper.py
  cbioportal_etl/scripts/maf_merge.py
  cbioportal_etl/scripts/resolve_config_paths.py
  cbioportal_etl/scripts/rna_merge_rename_expression.py
Labels: documentation, bix-dev

#84 🔧 Fix Solo Mode Bugs
  COLLABORATIONS/openPBTA/README.md
  README.md
  cbioportal_etl/cli.py
  cbioportal_etl/scripts/check_downloads.py
  cbioportal_etl/scripts/convert_fusion_as_sv.py
  cbioportal_etl/scripts/diff_studies.py
  cbioportal_etl/scripts/genomics_file_cbio_package_build.py
  cbioportal_etl/scripts/get_files_from_manifest.py
  cbioportal_etl/scripts/get_study_metadata.py
  cbioportal_etl/scripts/organize_upload_packages.py
  cbioportal_etl/steps.py
Labels: bug, bix-dev

#85 🔧 SOP cleanup
  README.md
  cbioportal_etl/STUDY_CONFIGS/all_studies_config_values.tsv
  cbioportal_etl/scripts/generate_config.py
  cbioportal_etl/scripts/genomics_file_cbio_package_build.py
  cbioportal_etl/scripts/get_files_from_manifest.py
  cbioportal_etl/scripts/organize_upload_packages.py
  docs/INCREMENTAL_UPDATES.md
  docs/INSTALL.md
  docs/WHOLE_STUDY_IMPORT.md
  images/etl_flowchart.png
  template_credentials/template.db.ini
  template_credentials/template.sevenbridges.ini
Labels: bug, documentation
